### ISSUE TITLE
textarea height "jumping" 

### ISSUE THREAD

**Issue by optyler** [monospaced/angular-elastic#101]
Hello,

I got a strange issue, with an elastic textarea, I link a gifv because I don't know how to explain this in english...

![bug](https://user-images.githubusercontent.com/10259/31539708-be452728-b009-11e7-9d90-2aa73fe12d25.gif)

This is my `haml`/`rails` code
```haml
.form-group.message
  %textarea.message.form-control.msd-elastic{:name => "message", :placeholder => "Message...", :rows => "1", required: "true", "ng-model" => "body"}
```

And the css 
```css
textarea.message {
  min-height: 52px;
}
```

other styles are done with bootstrap.

* angular-elastic v2.5.1
* Google Chrome Version 61.0.3163.100

**Comment by monospaced** [comment]
Archiving repository.
