### ISSUE TITLE
Setting maximum height

### ISSUE THREAD

**Issue by vogelsgesang** [monospaced/angular-elastic#12]
Is there a possibility to limit the size of the textbox?
I want to avoid the text area to grow arbitrarily large.

**Comment by msieurtoph** [comment]
The `overflow` property seems to be hard-coded to `hidden`. I think it would be better to have it forced to `auto`... And by the way, It would rather be forced only if undefined, and keep original value if this one has been specified by the designer.

I can provide a pull request if you agree
