### ISSUE TITLE
Disable resize:horizontal

### ISSUE THREAD

**Issue by TimDaub** [monospaced/angular-elastic#35]
Hi,

I've ran into the issue that your library sets the property 
`resize: horizontal` 

to all `<textarea>`s.

Is there a way to disable this?

**Comment by TimDaub** [comment]
Never mind, found the solution in the code myself:

`<textarea class="msd-elastic form-control" style="resize:none;"></textarea>`

will get rid of it.

**Comment by monospaced** [comment]
Yes, it won't set `resize: horizontal` if there is an existing resize rule or `none` or `vertical` on the element.

Could set this in CSS too, doesn't have to be an inline style.
