### ISSUE TITLE
Update Readme.md including guidelines for javascript inclusion

### ISSUE THREAD

**Issue by evilaliv3** [monospaced/angular-elastic#36]
While integrating angular-elastic inside globaleaks (https://github.com/globaleaks/GlobaLeaks/issues/1081) i've found that the Readme.md is missing some guidelines in order to include the javascript file of the library.

This is generally something to include in the Readme.md of an angular library that can improve the adoption by users.

e.g. you should state to include something like:

    <script src="components/angular-elastic/elastic.js"></script>

**Comment by monospaced** [comment]
Thanks for the contribution :+1: 

The reason I haven't done that, is that there is no way of knowing what path what be the correct one for a specific project. Or even if a script element is required, for example if using a grunt/gulp build process.

Hence why the install instruction in README are not prescriptive:

> Include the elastic.js script provided by this component in your app.
