### ISSUE TITLE
Event listener on resize

### ISSUE THREAD

**Issue by dnlmzw** [monospaced/angular-elastic#37]
First of all, thanks for your work. This directive was exactly what I needed. I was looking in the documentation and under the issues section for ways to listen on resize, but couldn't find anything. So I would just suggest that you put a description about the name of the event in your documentation:

```javascript
$rootScope.$on('elastic:resize', function(){ // Some actions })
```

**Comment by andRyanMiller** [comment]
Agreed - @dnlmzw's issue was the only way I could scope this functionality quickly. It seems a working example has been added to the project site (https://github.com/monospaced/angular-elastic/commit/ce45e7970d93d03f5fc2d0210299645df38c770f), but just not to the readme.

**Comment by monospaced** [comment]
I need to add this, thanks for the contribution.

**Comment by monospaced** [comment]
Added a while ago in this commit 516f96ce
