### ISSUE TITLE
request: expand to parent size.

### ISSUE THREAD

**Issue by chrisperfer** [monospaced/angular-elastic#38]
Hi. Before i go and try and implement something I thought I would ask, as your directive is already pretty awesome.

What I would like is to have the current functionality of msd-elastic, but with the option of it setting as minimum size the height of the containing element. The use case is, text areas within table cells. 

Thanks

Chris

**Comment by monospaced** [comment]
Elastic only adjusts the height of a textarea in relation to the content inside it. 

The essential height, min-height and max-height of the textarea are defined in CSS as usual.

So the CSS trick you need, is how to make a textarea expand to fill a parent table cell I guess.
