### ISSUE TITLE
feature: Fit to placeholder text

### ISSUE THREAD

**Issue by ArTiSTiX** [monospaced/angular-elastic#40]
Could you consider adding an option to enable automatic fitting to placeholder text ? (when textarea is empty).

Thank you for this simple directive, it's very time saving.

**Comment by monospaced** [comment]
Placeholder text does not resize the textarea, or effect it's box-model. 

So I think this would only be possible, if you didn't use the native placeholder attribute at all, and used a javascript placeholder instead, that is actually real text, not a pseudo element. So in the style of polyfills for placeholder support in old IE (ahem https://github.com/monospaced/angular-placeholder), but then apply that to all browsers. Then would have to figure out how to get the 2 behaviours (elastic and fake placeholders) to work in concert.

On balance, I think this is too complicated to add as an option to elastic. I prefer to leave the native textarea behaviour in place as much as possible. It would mean adding all the code to manage placeholder state, but only use this for 'auto size to placeholder' option. Then you'd end up with 2 different placeholder behaviours invoked by this directive.

**Comment by monospaced** [comment]
Oh and thanks for your contribution :)

**Comment by rgembalik** [comment]
I believe the behavior someone was looking for is to expand text area if its placeholder does not fit in it.
Here is my pull request on the case: https://github.com/monospaced/angular-elastic/pull/87
