### ISSUE TITLE
Respect textarea's row setting.

### ISSUE THREAD

**Issue by jarzuaga** [monospaced/angular-elastic#41]
Hi, 

I'm using your directive and it works great. One thing though. I'm setting the rows attribute of my textarea to 30, however when it loads it's much smaller than that and it lets me enter more than 30 rows of input. 

I'd love to see an attribute for the directive where you specify a range. Something like this:

`<textarea msd-elastic msd-elastic-min-rows="5" msd-elastic-max-rows="30"></textarea>`

That would make the textarea 5 rows tall on load and let it grow only up to 30 rows.

**Comment by monospaced** [comment]
I'm sure you could sort that out with CSS, as elastic just extends the native textarea.

You can use `rows` attribute to set the intrinsic rows (2 is the browser default), but the behaviour you need can all be achieved with CSS `height`, `min-height` and `max-height` properties.

**Comment by jarzuaga** [comment]
You're absolutely right. Thanks.

**Comment by monospaced** [comment]
You're welcome :)
