### ISSUE TITLE
Initial height of textarea adds empty line

### ISSUE THREAD

**Issue by jessebuitenhuis** [monospaced/angular-elastic#44]
I use your fantastic directive all over my site, but I keep walking into an issue. I create a textarea, which should have a height of 1 textline. The directive automatically adds an extra white line, when the area expands it fits perfectly, but when deleting all the text it falls back to two empty lines.

Is there a setting to control the initial height of the textarea? All my css gets overridden by the javascript heights set by the directive. 

Thanks a lot!

**Comment by monospaced** [comment]
```html
<textarea rows="1">
```
