### ISSUE TITLE
Works only when keyboard attach is false , in IONIC framework. 

### ISSUE THREAD

**Issue by scripterkaran** [monospaced/angular-elastic#53]

**Comment by fumitoito** [comment]
I have same problem in my iOS application like followings.

- **without** keyboard-attach directive
<img src="https://cloud.githubusercontent.com/assets/770377/8098244/5975e158-1028-11e5-9d5b-07838981b302.png" width="240">

- **with** keyboard-attach directive
<img src="https://cloud.githubusercontent.com/assets/770377/8098245/598089f0-1028-11e5-8b61-b1e8c62320be.png" width="240">

it is probably caused conflict between keyboard-attach and angular-elastic.

**Comment by monospaced** [comment]
Ah, ok. Thanks for the contribution :+1: 

I've started using Ionic, so will try and look into this.

I didn't know about this keyboard-attach directive, could be useful.

**Comment by eleva** [comment]
Hi, is there any solution for this?
I'm experiencing the same issue using keyboard-attach with latest version of ionic.

**Comment by VinceOPS** [comment]
Hi. No issue with keyboard-attach here, I just had to force the `height` of the footer bar to `auto` and remove all `min` or `max` height properties.
The textarea is growing and the parent footer-bar is growing with it.

**Comment by jdnichollsc** [comment]
Works perfect with Ionic 1.x https://market.ionic.io/plugins/ionic-elastichat-images
