### ISSUE TITLE
Problem with two-way binding

### ISSUE THREAD

**Issue by hyades** [monospaced/angular-elastic#54]
I am having something like

``` javascript
$http.get(path)
    .success(function(data){
    $scope.data = data;
    $rootScope.$broadcast('elastic:adjust'); // as mentioned in the docs
  });
```

Here `data` is modelled to the `textarea`

But this is an issue as expected. Sometimes the `textarea` is set to precise length, and sometimes it fills up the entire page (almost 4 times the expected size). Is this something to do with the `$digest` cycles?

**Comment by monospaced** [comment]
Hi

Did you get any further with this? Be good to see a plunker... And thanks for the contribution :+1:

**Comment by monospaced** [comment]
Archiving repository.
