### ISSUE TITLE
Max-height restriction

### ISSUE THREAD

**Issue by Jenin** [monospaced/angular-elastic#60]
Max-height only works if the style is inlined. if applying a class to the textarea element it will not work!

**Comment by monospaced** [comment]
I can't recreate this, max-height works for me wherever I apply it. Could be CSS specificity issue perhaps? Able to show a test case? Thanks.

**Comment by binarykitchen** [comment]
In addition I would recommend to remove `resize: none` when max height has been reached.

**Comment by Charlie-Hua** [comment]
Moving max-height from inline to class breaks my scroll (it doesn't show), however the textarea still honors the max-height value set in class.

**Comment by monospaced** [comment]
Closed due to inactivity
