### ISSUE TITLE
[Feature] Cleaner la popup de demande pour savoir ce que l'utilisateur recherche

### ISSUE THREAD

**Issue by MathildeLemee** [monospaced/angular-elastic#64]

**Comment by monospaced** [comment]
Je ne comprends pas.

**Comment by philippeluickx** [comment]
Literally means "Cleaner the request-popup to know what the user is searching". So even French won't help you there. Suggesting to close the issue.

**Comment by monospaced** [comment]
Thanks @philippeluickx !
