### ISSUE TITLE
Safari won't render textarea with 0 returns

### ISSUE THREAD

**Issue by geoffbalasi** [monospaced/angular-elastic#65]
When setting msd-elastic to have no returns in the textarea. Chrome renders correctly with a height of 32px and one line but Safari renders with a height of 48px as if there were 2 lines. 

Chrome: 
![screen shot 2015-08-05 at 12 39 55 pm](https://cloud.githubusercontent.com/assets/1933197/9092986/2cc09a8c-3b6f-11e5-8e48-0e791f607e72.png)

Safari:
![screen shot 2015-08-05 at 12 41 32 pm](https://cloud.githubusercontent.com/assets/1933197/9093041/6f772f62-3b6f-11e5-8207-7539e50e6cde.png)

What should i do to get safari to render with only 1 line to start?

**Comment by monospaced** [comment]
add `rows="1"` attribute?
