### ISSUE TITLE
Height too long on page load?

### ISSUE THREAD

**Issue by hardikbhatia** [monospaced/angular-elastic#67]
Hi,

I am using elastic.js in my bootstrap model but the problem is when i open up my model first time , then the textarea height is too long than the text .When i edit something in it, close the model then it comes fines but if i refersh the page then again the textarea is too long.Below is the code for it.

<div id="myModal" class="modal fade" ng-repeat="c in CoverPageData" role="dialog" aria-labelledby="gridSystemModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        @*<button type="button" id="closeDialogBox" onclick="closeDialogBox();return false;" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>*@
                        <h4 class="modal-title" id="gridSystemModalLabel">SpecialBillingInstructions</h4>
                    </div>

```
                <div class="modal-body">
                    <div class="container-fluid">
                        <div>
                            <div>
                                <dl style="margin-bottom: 0">
                                    <dd>
                                        <textarea class="animate msd-elastic: \n;" placeholder="" style="width: 100%;" id="SPBI" ng-model="c.SpecialBillingInstructionsModel" ng-blur="Save(c.SpecialBillingInstructionsModel)"></textarea></dd>
                                </dl>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <dl>
                                    <dt>Transfer All Instructions</dt>
                                </dl>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-3">
                                <dl>
                                    <dt>Transfer Matter for Fee</dt>
                                    <dd>
                                        <input id="FeeTransferMatter" type="text" ng-model="c.FeeTransferModel" ng-blur="SaveTransf(c.FeeTransferModel,c.CostTransferModel,c.ChargeTransferModel)" style="width: 80px; height: 30px" /></dd>
                                </dl>
                            </div>
                            <div class="col-xs-3 ">
                                <dl>
                                    <dt>Transfer Matter for Cost</dt>
                                    <dd>
                                        <input id="CostTransferMatter" type="text" ng-model="c.CostTransferModel" ng-blur="SaveTransf(c.FeeTransferModel,c.CostTransferModel,c.ChargeTransferModel)" style="width: 80px; height: 30px" /></dd>
                                </dl>
                            </div>
                            <div class="col-xs-3 ">
                                <dl>
                                    <dt>Transfer Matter for Charge</dt>
                                    <dd>
                                        <input id="ChargeTransferMatter" type="text" ng-model="c.ChargeTransferModel" ng-blur="SaveTransf(c.FeeTransferModel,c.CostTransferModel,c.ChargeTransferModel)" style="width: 80px; height: 30px" /></dd>
                                </dl>
                            </div>
                        </div>                            
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
        <!-- /.modal-content -->
    </div>
```

**Comment by ericmmartin** [comment]
I am having the same issue, but can't recreate it outside of my application. I wondered if it was Bootstrap, but, no such luck...

http://embed.plnkr.co/ShrdAFHxO3PXck3k1pYT/preview

@hardikbhatia did you figure out the cause or a solution?

**Comment by hkrupnik** [comment]
@hardikbhatia  @ericmmartin  I was having this same issue. It seems to be caused by the msd-elastic directive not detecting a change (and therefore not adjusting the textarea height correctly) when the ng-model first loads (on page/modal open) and populates the textarea with whatever is inside your ng-model. Maybe @monospaced can confirm?

The solution I used was to bind the ng-model value to the directive. That way, when the ng-model value is loaded initially (on page/modal open), the msd-elastic directive detects a change right away and recalculates the textarea height even before the user edits the textarea.

So to implement this in your own code, just add `scope:{ ta-text: '=', },` code to your elastic.js file below line 26:
```javascript
return {
        require: 'ngModel',
        restrict: 'A, C',
        scope: {
          taText: '=', //ng-model text from the textarea
        },
        link: function(scope, element, attrs, ngModel) {
```

And on your html textarea, add this:
```html
<textarea msd-elastic="\n" ta-text="c.SpecialBillingInstructionsModel" ng-model="c.SpecialBillingInstructionsModel" ></textarea>
```
Note that msd-elastic is no longer set using `class="msd-elastic: \n;"` but instead using `msd-elastic="\n` and the new directive scope value `ta-text` contains the same ng-model value (`c.SpecialBillingInstructionsModel`) as the textarea.

For more info on passing strings, scope value, and functions to directives see this link:
http://www.ng-newsletter.com/posts/directives.html
```javascript
scope: {
          // '=', -- Bind the ngModel value
          // '&', -- Pass a function
          // '@'  -- Pass a string
          //source: http://www.ng-newsletter.com/posts/directives.html
          taText: '=', //ng-model text from the textarea
        },
```

**Comment by daviddutch** [comment]
This doesn't seem to fix it for me... Does anyone have a solution?

**Comment by brunopaz** [comment]
Hey, I had the same issue. The textarea is inside a bootstrap panel and the height was immensely large. My provisional solution was to change on elastic.js, line 200:

**Comment by piotrkorlaga** [comment]
got the same problem - above workaround fixed it

**Comment by ret0** [comment]
same here: above workaround fixed it

**Comment by Pumych** [comment]
got the same problem - above workaround fixed it too. Does this fix can be added to bower repository

**Comment by monospaced** [comment]
Archiving repository.
