### ISSUE TITLE
How to set initial height of textarea ?

### ISSUE THREAD

**Issue by yashvekaria** [monospaced/angular-elastic#71]
Hi, I am using msd-elastic as a directive. But by default is seting height as 64px (in chrome). I am even not adding any "\n"(new line charcter behind it).   I wanted to set as 46px initially across all browser. Any appropriate suggestions ?

**Comment by monospaced** [comment]
You may need to set `rows="1"` (browsers default to 2)

Besides this, you may have some CSS in play. You should be able to control the empty height with CSS `min-height`

**Comment by soferio** [comment]
As said by monospaced, the problem is solved for me by adding:

style='min-height: 1em' rows='1'

>

**Comment by monospaced** [comment]
Closed due to inactivity (also this can be resolved outside of elastic with HTML/CSS).
