### ISSUE TITLE
resize: vertical

### ISSUE THREAD

**Issue by tandvu** [monospaced/angular-elastic#74]
I know this directive automatically resize the height based on the content.  However, I still like the fact that I can manually drag to expand the height of the textarea.  Is it possible?

Thank you,

Tan

**Comment by monospaced** [comment]
Not really. 

Elastic works by measuring the height of an offscreen 'mirror' of the textarea. Dragging the handle to resize the actual textarea would not be reflected in the offscreen mirror, so the elastic resizing would no longer work. Therefore the directive removes any `resize: vertical` CSS that has been declared.

However, you can use `resize: horizontal` if you wish.
