### ISSUE TITLE
How to ensure sizing adjusted when text area is initially hidden

### ISSUE THREAD

**Issue by GeoffCox** [monospaced/angular-elastic#82]
I found that the initial size is not adjusted properly if the textarea starts out hidden and is then shown via an ng-show (or ng-hide) binding later.  

Adding this line fixes the problem in some cases:

```
scope.$watch(attrs.ngShow, forceAdjust);
```

I added this right after

```
$win.bind('resize', forceAdjust);
```

**Comment by markediez** [comment]
Did you add the above code in elastic.js or your own code? I'm having the same issue.

**Comment by jjoekoullas** [comment]
I ran into this as well.  Using `ng-if` was a pretty painless workaround for myself.

**Comment by monospaced** [comment]
Archiving repository.
