### ISSUE TITLE
make ngmodel dependency optional?

### ISSUE THREAD

**Issue by electronicott** [monospaced/angular-elastic#83]
i am working on a project where the text areas are not data bound to a model,
but i would still like to use elastic to resize them.

would it be possible to change the ngModel requirement to ?ngModel
and thus removing the scope watcher, if not specified?

thank you

**Comment by monospaced** [comment]
Angular docs state that `ng-model` is a required attribute of an angular textarea:

https://docs.angularjs.org/api/ng/directive/textarea

So angular elastic also requires this attribute.

**Comment by electronicott** [comment]
thanks for your reply, but i think that's a problem with the angular docs, as their code on github states:
[https://github.com/angular/angular.js/blob/master/src/ng/directive/input.js](url):1676
```
var inputDirective = ['$browser', '$sniffer', '$filter', '$parse',
    function($browser, $sniffer, $filter, $parse) {
  return {
    restrict: 'E',
    require: ['?ngModel'],
```

**Comment by monospaced** [comment]
I get a 404 on that link.

**Comment by electronicott** [comment]
ah sorry, forgot the url... try again now

**Comment by monospaced** [comment]
Archiving repository.
