### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by paulhickman-a365** [monospaced/angular-elastic#85]
Do you plan on producing an Angular 2 version?

**Comment by okonon** [comment]
this would be wicked awesome to add support for angular 2. How would one start on such task? @monospaced

**Comment by fiznool** [comment]
I've created [angular2-elastic](https://github.com/fiznool/angular2-elastic/) to help here. It doesn't quite have all the bells and whistles of this implementation, but it works well for basic Angular 2 textareas, and it's also compatible with Ionic 2.

Thanks to @monospaced for the inspiration and a fantastic library. I hope to incorporate some of the additional ideas from here (e.g. recalculating on window resize) soon.

**Comment by fiznool** [comment]
Providing an update here. Since Angular 4 has been released, the library mentioned in the previous comment is now known as [ng-elastic](https://github.com/fiznool/ng-elastic/) and supports window resizing. Please consider if you need support for Angular/Ionic 2+.
