### ISSUE TITLE
Bug is the $watch function

### ISSUE THREAD

**Issue by prawnz** [monospaced/angular-elastic#86]
I was using KendoUi Grid with the code and when you select the text area in an inline editing mode, the $modelValue is set to null which throw an error. The bug is in the following code, 
 scope.$watch(function () {
          return ngModel.$modelValue;            
          }, function(newValue) {
            forceAdjust();
          });

I've put in a temporary fix which is to ensure it is coded defensively by doing 
 scope.$watch(function () {
              if (ngModel) {
                  return ngModel.$modelValue;
              }
              else {
                  return '';
              }
          }, function(newValue) {
            forceAdjust();
          });

Please take note if you have encountered this issue which is very common when the model is set to null..

**Comment by monospaced** [comment]
Sounds like a KendoUI issue, but thanks for pointing out the fix, hopefully could be useful to others 👍
