### ISSUE TITLE
Zooming in browser doesn't resize textarea

### ISSUE THREAD

**Issue by mariusz** [monospaced/angular-elastic#88]
So we have some visually impaired users who tend to up their page zoom to 150% or more. Unfortunately even though text takes more space now, the textarea doesn't scale and text gets cut off. I know that's an edge case, but maybe there's some simple workaround?

**Comment by monospaced** [comment]
I don't experience this issue, in Chrome OSX I can zoom the test page to any size, and the elastic functionality is unaffected: http://monospaced.github.io/angular-elastic/

Could you perhaps provide some more details, steps to recreate?

**Comment by monospaced** [comment]
Unable to recreate, closed due to inactivity.
