### ISSUE TITLE
specify rows not work

### ISSUE THREAD

**Issue by apellicc** [monospaced/angular-elastic#93]
Hi, on Ionic the property rows isn't working on this exemple :

<textarea rows="4"
class="msd-elastic"
data-ng-model="modal.controller.action.description"
placeholder="Type or copy your description here."
/>

Does anyone have an idea ?

**Comment by monospaced** [comment]
`rows` would be overridden by any CSS height declarations, maybe look at that?

**Comment by monospaced** [comment]
Archiving repository.
