### ISSUE TITLE
Incorrect height when browser zoom is more than 100% and textarea width is 100%

### ISSUE THREAD

**Issue by prp1** [monospaced/angular-elastic#94]
How to reproduce:
- open google chrome
- increase your browser zoom
- open http://jsfiddle.net/2ph33L0t/12/
- change browser size so that last line of textarea has only one word - "dapibus_"
- refresh the page

Result: word "dapibus_" is not visible.

This is a very dangerous bug as not visible text can mislead users, what can result in very serious consequences.

**Comment by monospaced** [comment]
Archiving repository.
