### ISSUE TITLE
support for dynamic value of the textarea's rows attribute

### ISSUE THREAD

**Issue by max-l** [monospaced/angular-elastic#98]
msd-elastic allows setting the text area's row attribute with a constant.

ex: this works: 

    <textarea msd-elastic ng-model="field.value" rows="5"></textarea>

but not this : 

     scope.rows = 5 

    <textarea msd-elastic ng-model="field.value" rows="{{ rows }}"></textarea>

in the later case, the rows attribute is ignored

**Comment by monospaced** [comment]
Archiving repository.
